jobs:
  bolo-buildx:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      id: date
      name: Get current date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    - continue-on-error: true
      id: prep
      name: Prepare
      run: 'TAG=$(echo $GITHUB_REF | cut -d / -f 3)

        IMAGE="tangcuyu/bolo-solo"

        echo ::set-output name=image::${IMAGE}

        echo ::set-output name=tag::${TAG}

        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

        '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - continue-on-error: true
      id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - continue-on-error: true
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: '${{ runner.os }}-buildx-

          '
    - continue-on-error: true
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: false
        tags: '${{ steps.prep.outputs.image }}:latest

          '
    - continue-on-error: true
      name: Move cache
      run: 'rm -rf /tmp/.buildx-cache

        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

        '
name: Bolo-Build-Amd64
on:
  repository_dispatch:
    types: trigger-ga___docker-image-builder.yml
